config/routes.rb
Rails.application.routes.draw do
  resources :users
  #resources :shows
  resources :reviews
  resources :watch_later

  resources :shows do
    collection do
        get 'search'
    end
    resources :reviews

end
  

  root 'sessions#welcome'

  get '/welcome', to: 'sessions#welcome'
  get '/signup', to: 'sessions#signup'
  post '/signup', to: 'users#signup'

  get '/login', to: 'sessions#login'
  post '/signin', to: 'sessions#signin'

  delete '/logout', to: 'sessions#logout'
  get '/logout', to: 'sessions#logout'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/reviews', to: 'reviews#index'
  get '/reviews/:id/edit', to: 'reviews#edit'
  get '/reviews/:id', to: 'reviews#index'
  
  #post '/shows/:id/reviews/new', to: 'shows#new'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :show
end

app/models/show.rb
class Show < ActiveRecord::Base
    has_many :reviews
    has_many :users, through: :reviews

    validates :title, presence: true
    validates :genre, presence: true 
    validates :description, presence: true 
    validates :seasons, presence: true
    validates :rating, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :reviews
    has_many :shows, through: :reviews

    validates :email, presence: true
    validates :username, presence: true
   
    has_secure_password

end

app/models/watch_later.rb
class WatchLater < ActiveRecord::Base
    belongs_to :user
    belongs_to :show 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?

    private
    
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :set_show

    def index 
        @reviews = Review.all
    end

    def new 
        @review = Review.new
    end

    def show
        if @review.user_id == current_user.id
          render 'show'
        else 
          redirect_to show_path(@show)
        end
    end

    def edit
        if @review.user_id == current_user.id
          render 'edit'
        else 
        redirect_to show_path(@show)
        end
    end

    def create
        @review = Review.create(review_params)
        @review.user_id = current_user.id
        @review.show_id = @show.id
          if @review.save
            redirect_to @show, notice: 'Review was successfully created.'
          else
            render 'new'
          end
      end

    def update
        @review.update(review_params)
    end

    def destroy
        @review.destroy
        redirect_to @show
    end

    def show
        if @review.blank?
            redirect_to new_review_path
        end
       
    end


    private

    def review_params
        params.require(:review).permit(:comment, :rating, :user_id, :show_id)
    end

    def set_review
       @review = Review.find_by(params[:id])
    end

    def set_show
       @show = Show.find_by(params[:show_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def signup
        @user = User.new
    end

    def signin
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
    
            redirect_to shows_path
        else
            flash[:error] = "Looks like your email or password is incorrect"
            redirect_to login_path
        end
    end

    def login
        @user = User.new
    end

    def logout
        session.delete(:user_id)    
        redirect_to root_path
    end

    def omniauth 
        user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.email = auth['info']['email']
            u.username = auth['info']['name']
            u.password = SecureRandom.hex(15)
        end
        if user.valid?
            session[:user_id] = user.id
            flash[:message] = "Logging In!"
            redirect_to shows_path
        end
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :set_show, only: [:show, :edit, :update, :destroy]

    def search
        if params[:search].present?
            @shows = Show.search(params[:search])
        else
            @show = Show.all
        end
    end

    def index
        @shows = Show.all
    end

    def new
        @show = Show.new
    end

    def edit
    end

    def create
        @show = Show.new(show_params)
        if @show.save
            redirect_to @show 
        else
            render 'new'
        end
    end

    def update
        if @show.update(show_params)
            redirect_to @show 
        else
            render 'edit'
        end
    end

    def destroy
        show.delete
    end

    def show
        @reviews = Review.where(show_id: @show.id).order("created_at DESC")
    end

    private 

    def show_params
        params.require(:show).permit(:title, :genre, :description, :seasons, :rating)
    end

    def set_show
       @show = Show.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new 
        @user = User.new
    end

    def signup
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/controllers/watch_later_controller.rb
class WatchLaterController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
    <li><%= link_to "Animes", shows_path, class: "active" %></li>
    <li><%= link_to "Reviews", reviews_path, class: "active" %></li>
    <!---- link to watch later -----!>
    
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeyAnime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= render 'layouts/header' %>
  
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <div class="form-group">
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :comment %><br></h3>
    <%= f.text_area :comment, class: "form-control", placeholder: "Comment" %>
  </div>
  <div class="field"> 
    <h3><%= f.label :rating%><br></h3>
    <%= f.number_field :rating, max: 5, min:1, class: "form-control" %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Your Review Here!</h1>

<%= render 'form' %>
<%= link_to 'Back', @review %> 
<%= link_to "Delete", review_path(@review), method: :delete %>

app/views/reviews/index.html.erb
<h1> Your Reviews </h1>

  <% @reviews.each do |review| %>

    

    <% @show.title %>
  <h2>Comment: <%= review.comment %></h2>
  <h2>Rating: <%= review.rating %></h2>
  <%= link_to "#{review.comment}", review_path(review) %>
 
  <% end %>
  
  <% link_to 'Back', shows_path(@show) %>

app/views/reviews/new.html.erb
<h1>New Review for: <!/h1>

<%= @show.title %>


<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<h1><%= @show.title %></h1>

<h2>Comment:</h2>
<h3><%= @review.comment %><br></h3>
<h2>Rating:</h2>
<h3><%= @review.rating %><br></h3>

<%= link_to 'Back', show_path(@show)%>
<%= link_to 'Update', edit_review_path(@review) %>
<%= link_to "Delete", review_path, method: :delete %>

app/views/shows/_errors.html.erb
<% if show.errors.any? %>
<h1><%= pluralize(show.erros.count, "error") %><br>
<% show.error.each do |e|
    <%= error.message %>
    <% end %>
<% end %>

app/views/shows/_form.html.erb
<%= form_for @show do |f|%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
    <% if @show.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@show.errors.count, "error") %></h2>
    <ul>
    <% @show.errors.messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Title", required: true%>
    </div>
    <%= f.label :genre %><br>
    <%= f.text_field :genre, class: "form-control", placeholder: "Genre", required: true%>
    </div>
    <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", placeholder: "Description", required: true%>
    </div>
    <div class="field">
    <%= f.label :seasons %><br>
    <%= f.text_field :seasons, class: "form-control", placeholder: "Seasons", required: true%>
    </div>
    <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: "form-control", placeholder: "Rating", required: true%>
    </div>
    <div class="actions">
    <%= f.submit %>
    </div>
    <% end %>

app/views/shows/edit.html.erb
<h1>Editing</h1>
<%= render 'form' %>
<%= link_to 'Back', @show %> 

app/views/shows/index.html.erb
<h1>Animes</h1>

<% @shows.each do |show| %>
 <td><%= show.title %></td><br>

<td><%= link_to 'Details', show %></td><br>


<% end %>

<br>
<%= link_to 'New Anime', new_show_path %>
<%= button_to "Log Out", logout_path, method: 'delete' %>

app/views/shows/new.html.erb
<h1>New Anime</h1>
<%= render 'form' %>
<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<h1>Title:</h1>
    <%= @show.title %>
<h1>Genre:</h1>
    <%= @show.genre %>
<h1>Description:</h1>
    <%= @show.description %>
<h1>Seasons: <%= @show.seasons %></h1>
<h1>Rating: <%= @show.rating %></h1>

<%= link_to 'New Review', new_review_path(@review) %>

<%= link_to 'Back', shows_path %>

app/views/users/_form.html.erb
<div class="login">
    <div class="container">
        <div class="form">
        <%= form_for(@user) do |f| %>
        <%= f.text_field :username, :placeholder => "username" %>
        <%= f.email_field :email, :placeholder => "Email" %>
        <%= f.password_field :password, :placeholder => "Password" %>
        <%= f.submit "Login", class: "btn-submit" %>
        <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="login">
    <div class="container">
        <div class="form">
        <h1>Sign Up</h1>
        <%= form_for(@user) do |f| %>
        <%= f.text_field :username, :placeholder => "username" %>
        <%= f.email_field :email, :placeholder => "Email" %>
        <%= f.password_field :password, :placeholder => "Password" %>
        <%= f.submit "Create an account", class: "btn-submit" %>
        <% end %>
        </div>
    </div>
</div>

app/views/watch_later/index.html.erb
<h1>Hello there! uwu </h1>